{% set name = "vapeplot" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 50cda617664f69873e459d82eeef72a43f7511a6397bc1b6411199645239a4f2

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy

test:
  requires:
    - python {{ python_min }}
  imports:
    - vapeplot

about:
  home: https://github.com/dantaki/vapeplot/
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: matplotlib extension for vaporwave aesthetics
  dev_url: https://github.com/dantaki/vapeplot/

extra:
  recipe-maintainers:
    - timkpaine
